Initial commit
alibabacloud-automation/terraform-alicloud-ess-alb pull request #1
Opened 2022-03-24 09:06 UTC by Wanghx0991

2022-03-24 09:23 UTC, xiaozhu36 requested changes

2022-03-24 09:23 UTC, xiaozhu36 commented on main.tf
> +resource "alicloud_slb_load_balancer" "balancer" {
写错了吧，标题是 alb ，这里怎么是 slb

2022-03-30 13:45 UTC, xiaozhu36 requested changes

2022-03-30 13:45 UTC, xiaozhu36 commented on main.tf
> +  protocol          = "HTTP"
这个只能是 HTTP 么

2022-03-30 13:45 UTC, xiaozhu36 commented on main.tf
> +        server_group_id = alicloud_alb_server_group.alb_server_group.0.id
这个地方应该是 local. server_group_id 吧

2022-03-30 14:05 UTC, Wanghx0991 commented on main.tf
> +  protocol          = "HTTP"
Done

2022-03-30 14:05 UTC, Wanghx0991 commented on main.tf
> +        server_group_id = alicloud_alb_server_group.alb_server_group.0.id
Done

2022-03-31 02:35 UTC, xiaozhu36 requested changes

2022-03-31 02:35 UTC, xiaozhu36 commented on variables.tf
> +  default     = null
既然有default，那就写上，其他的也检查下

2022-03-31 02:35 UTC, xiaozhu36 commented on README.md
> +Apache 2 Licensed. See LICENSE for full details.
协议不对

2022-03-31 03:05 UTC, merged